name: pc_classification
channels:
  - defaults
  - anaconda
  - conda-forge
  - open3d-admin
dependencies:
  - python==3.6.*
  - nb_conda
  - h5py
  - scikit-learn
  - scikit-image
  - jupyterlab
  - easydict
  - open3d
  - tensorflow-gpu==1.14.1
  - pip:
    - opencv-python
    - transforms3d
    - gpustat
    - mock
    - future